#!/usr/bin/bash

# ./testmodetwo N M1 M2 M3 T MULTS

rm -rf work
vlib work
./testgen 2 $1 $2 $3 $4 $5 $6 
./gen 2 $1 $2 $3 $4 $5 $6 const_$1_$2_$3_$4_$5_$6.txt 
vlog multi_$1_$2_$3_$4_$5_$6.sv tb_multi_$1_$2_$3_$4_$5_$6.sv 
vsim -c tb_multi_$1_$2_$3_$4_$5_$6 -do "run -all; quit"
